# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A32LH8fdeklPj1atbg9L_OMyDiE55leg
"""

import pandas as pd
import matplotlib as plt

df = pd.read_csv("data01.csv", header=0)

col = df['median_house_value']

mdian = col.median()
print(mdian)

print("\n\n\n")

rooms = df['total_rooms']

less = 0

for e in rooms:
  if e < 500:
    less += 1

print(less)

age = df['housing_median_age']

indixes = df.index[age < 25]

print("\n\n\n")

for e in indixes:
  print(df.iloc[e])
  print("\n")

df.plot(kind='scatter', x='longitude', y='latitude')